lib/api/bttv_api.dart, lib/api/ffz_api.dart, lib/api/seventv_api.dart, lib/api/twitch_api.dart, lib/core/auth/auth_store.dart, lib/core/auth/auth_store.g.dart, lib/core/user/user_store.dart, lib/main.dart, lib/screens/channel/chat/details/chat_users_list.dart, lib/screens/channel/stores/chat_assets_store.dart, lib/screens/channel/stores/chat_assets_store.g.dart, lib/screens/channel/stores/chat_details_store.dart, lib/screens/channel/stores/chat_details_store.g.dart, lib/screens/channel/stores/chat_store.dart, lib/screens/channel/stores/video_store.dart, lib/screens/channel/video_chat.dart, lib/screens/home/search/search_results_categories.dart, lib/screens/home/search/search_results_channels.dart, lib/screens/home/stores/categories_store.dart, lib/screens/home/stores/categories_store.g.dart, lib/screens/home/stores/list_store.dart, lib/screens/home/stores/list_store.g.dart, lib/screens/home/stores/search_store.dart, lib/screens/home/top/categories.dart, lib/screens/home/top/category_streams.dart, lib/screens/home/widgets/category_card.dart, lib/screens/home/widgets/stream_card.dart, lib/screens/home/widgets/streams_list.dart, lib/screens/settings/widgets/profile_card.dart, lib/widgets/profile_picture.dart
=> Refactor API requests and improved error handling

lib/api/twitch_api.dart, lib/constants/constants.dart, lib/core/auth/auth_store.dart, lib/models/emotes.dart, lib/models/emotes.g.dart, lib/screens/channel/chat/chat.dart, lib/screens/channel/chat/details/chat_details.dart, lib/screens/channel/chat/details/chat_users_list.dart, lib/screens/channel/chat/emote_menu/emote_menu.dart, lib/screens/channel/chat/emote_menu/emote_menu_panel.dart, lib/screens/channel/chat/emote_menu/emote_menu_section.dart, lib/screens/channel/chat/emote_menu/recent_emotes_panel.dart, lib/screens/channel/chat/widgets/chat_bottom_bar.dart, lib/screens/channel/stores/chat_assets_store.dart, lib/screens/channel/stores/chat_assets_store.g.dart, lib/screens/channel/stores/chat_store.dart, lib/screens/channel/stores/video_store.dart, lib/screens/channel/video/video.dart, lib/screens/channel/video/video_overlay.dart, lib/screens/channel/video_chat.dart, lib/screens/home/home.dart, lib/screens/home/search/search.dart, lib/screens/home/search/search_results_channels.dart, lib/screens/home/widgets/stream_card.dart, lib/screens/settings/sections/video_settings.dart, lib/screens/settings/stores/settings_store.dart, pubspec.lock, pubspec.yaml
Beta 9 Release
- Added new "Recent Emotes" section to emote menu
- Added English usernames next to non-English channel names (Thanks to /u/DanMizu for reporting!)
- Improved tap to dismiss behavior across the app, such as tapping the video player to dismiss keyboard (Thanks to /u/Icoryx for reporting!)
- Tweaked landscape/theater mode so that the system UI doesn't intrude
=> Merge latest changes from develop into main (Beta 9)

lib/constants/constants.dart, lib/models/emotes.dart, lib/models/irc.dart, lib/screens/channel/chat/emote_menu/emote_menu_section.dart, lib/screens/channel/chat/emote_menu/recent_emotes_panel.dart, lib/screens/channel/chat/widgets/chat_message.dart, lib/screens/settings/sections/chat_settings.dart, lib/screens/settings/stores/settings_store.dart, lib/screens/settings/stores/settings_store.g.dart
=> Apply emote sizes from FFZ/7TV APIs to chat and emote menu

lib/screens/channel/chat/widgets/chat_message.dart, lib/screens/settings/sections/chat_settings.dart, lib/widgets/profile_picture.dart, pubspec.lock, pubspec.yaml
- Fixed gray screen caused by new /announce command
=> Release v1.2.1

ios/Podfile.lock, lib/core/auth/auth_store.dart, lib/main.dart, lib/models/irc.dart, lib/screens/channel/chat/chat.dart, lib/screens/channel/chat/details/chat_users_list.dart, lib/screens/channel/chat/widgets/chat_bottom_bar.dart, lib/screens/channel/stores/chat_store.dart, lib/screens/channel/video/video_overlay.dart, lib/screens/channel/video_chat.dart, lib/screens/home/search/search.dart, lib/screens/settings/sections/account_settings.dart, pubspec.lock, pubspec.yaml
- Improved hints in text fields
- Improved chat scrolling behavior when the keyboard or emote menu is shown/hidden
- Fixed existing and/or outdated tokens not validating properly
- Fixed certain links in chat not launching (Android)
=> Release v1.2.2

lib/screens/channel/chat/widgets/chat_bottom_bar.dart
=> Change chat keyboard action to send

lib/screens/channel/chat/chat.dart, lib/screens/channel/chat/widgets/chat_bottom_bar.dart, lib/screens/channel/stores/chat_store.dart, lib/screens/channel/stores/chat_store.g.dart, lib/screens/channel/stores/video_store.dart, lib/screens/channel/video/video_overlay.dart, lib/screens/channel/video_chat.dart, lib/screens/settings/sections/chat_settings.dart, lib/screens/settings/stores/settings_store.dart, lib/screens/settings/stores/settings_store.g.dart
=> Add landscape chat overlay, chat side, and size options

ios/Podfile.lock, lib/screens/channel/stores/video_store.dart, lib/screens/channel/stores/video_store.g.dart, lib/screens/channel/video_chat.dart, pubspec.lock, pubspec.yaml
=> Add rotate button to overlay

lib/screens/channel/chat/details/chat_users_list.dart, lib/screens/channel/chat/widgets/chat_bottom_bar.dart, lib/screens/channel/stores/chat_details_store.dart, lib/screens/channel/stores/chat_details_store.g.dart, lib/screens/channel/stores/chat_store.dart, lib/screens/channel/stores/chat_store.g.dart, lib/screens/settings/sections/chat_settings.dart, lib/screens/settings/stores/settings_store.dart, lib/screens/settings/stores/settings_store.g.dart
=> 143 autocompletes for mentions

lib/screens/channel/chat/chat.dart, lib/screens/channel/chat/widgets/chat_message.dart, lib/screens/channel/chat/widgets/chat_user_modal.dart, lib/screens/settings/sections/chat_settings.dart
- Refactored the chat message widget to make them more tappable vertically
- Recent messages will now automatically update in the user modal
=> Refactor chat message widget and other chat fixes

android/app/src/main/AndroidManifest.xml, lib/models/emotes.g.dart, lib/models/irc.dart, lib/screens/channel/chat/chat.dart, lib/screens/channel/chat/details/chat_modes.dart, lib/screens/channel/stores/chat_store.dart, lib/screens/channel/stores/chat_store.g.dart, lib/screens/channel/stores/video_store.dart, lib/screens/channel/video_chat.dart, lib/screens/settings/sections/video_settings.dart, lib/screens/settings/stores/settings_store.g.dart, pubspec.lock, pubspec.yaml
=> Add PiP to Android and optimize chat

lib/screens/channel/stores/chat_store.dart, lib/screens/settings/sections/chat_settings.dart, lib/screens/settings/stores/settings_store.dart, lib/screens/settings/stores/settings_store.g.dart, pubspec.yaml
=> Add option to prevent sleep in chat-only mode

lib/screens/channel/video_chat.dart, lib/screens/settings/sections/chat_settings.dart, lib/screens/settings/stores/settings_store.dart, lib/screens/settings/stores/settings_store.g.dart
=> Add options to override landscape cutout

lib/screens/channel/video_chat.dart
=> Add ability to toggle fullscreen with double tap in landscape mode

lib/models/irc.dart, lib/screens/channel/chat/widgets/chat_message.dart
Adds replied messages to replying chat messages.
If a chat message is replying to a specific message, the message being replied to will now render right above. Basically how it is in the native Twitch web chat.
=> Add replied message to replies

android/app/src/main/kotlin/com/tommychow/frosty/MainActivity.kt, lib/screens/channel/channel.dart, lib/screens/channel/video/video.dart, lib/screens/channel/video/video_overlay.dart, lib/screens/channel/video/video_store.dart, lib/screens/home/stream_list/stream_card.dart, lib/screens/settings/stores/settings_store.dart, lib/screens/settings/stores/settings_store.g.dart, lib/screens/settings/video_settings.dart, lib/widgets/uptime.dart, pubspec.lock, pubspec.yaml
Closes #198 (see the issue for more details)
=> Add auto PiP on Android and redesign stream overlay

ios/Podfile.lock, lib/screens/channel/chat/chat.dart, lib/screens/channel/chat/widgets/chat_user_modal.dart, lib/screens/channel/chat/widgets/reply_thread.dart, lib/screens/settings/chat_settings.dart, lib/theme.dart, pubspec.lock
This PR upgrades the project to Flutter 3.16 and upgrades the packages.
=> Upgrade to Flutter 3.16

lib/screens/channel/chat/widgets/chat_bottom_bar.dart, lib/theme.dart
=> Fix multiline message clipping text fields

lib/screens/channel/chat/widgets/chat_message.dart
This PR improves the design of chat alerts and highlights so that they look more similar to the ones seen on the Twitch and 7TV web chat.
=> Improve chat alerts and highlights design

lib/models/irc.dart
=> Fix own display name not showing in chat

lib/models/emotes.dart, lib/models/emotes.g.dart
=> Fix animated FFZ emotes not animating

lib/screens/channel/chat/chat.dart, lib/screens/channel/chat/stores/chat_assets_store.dart, lib/screens/channel/chat/stores/chat_assets_store.g.dart, lib/screens/channel/chat/stores/chat_store.dart, lib/screens/channel/chat/widgets/chat_bottom_bar.dart, lib/screens/settings/chat_settings.dart, lib/screens/settings/stores/settings_store.dart, lib/screens/settings/stores/settings_store.g.dart
=> Add options to disable emotes and badges

lib/screens/channel/video/video_store.dart
adds a MutationObserver with a max timeout of 10 seconds, if it finds the content warning button, clicks it.
related to issue #404
=> accept content warning automatically

lib/screens/channel/video/video_overlay.dart, lib/screens/channel/video/video_store.dart
I fixed issue with displaying qualities and with displaying latency on Android devices. Also improved user experience and remembering last chosen stream quality.
=> Fix latency and stream qualities, improve ux

lib/screens/channel/chat/widgets/chat_bottom_bar.dart
=> Unfocuses chat text input on tap outside
