tommyxchow/frosty

- lib/screens/channel/stores/video_store.dart
- lib/screens/channel/stores/video_store.g.dart
- lib/screens/channel/video/video_overlay.dart
This PR adds a sleep timer accessible through an icon button on the video overlay. The user is able to set their desired hours and/or minutes which will then initiate a cancellable countdown. When this countdown reaches zero, the app will exit and let the user's system sleep setting take over.
Closes #79
> Implement sleep timer

- lib/screens/channel/stores/video_store.dart
- lib/screens/channel/video/video_overlay.dart
Apple probably won't approve of exiting the app programmatically based on their guidelines, so going ahead with pop like other apps.
> Use pop instead of exit for sleep timer

- lib/api/ffz_api.dart
- lib/api/seventv_api.dart
- lib/screens/channel/stores/chat_assets_store.dart
- lib/screens/channel/stores/chat_assets_store.g.dart
- lib/screens/channel/stores/chat_store.dart
When a channel changes their name, FFZ/7TV emote endpoints for the channel name are not updated immediately. This PR will utilize the channel's persistent id to check for emotes instead.
Fixes #115
> Fix FFZ/7TV emotes on certain channels

- lib/models/emotes.dart
- lib/models/emotes.g.dart
- lib/screens/channel/chat/emote_menu/emote_menu.dart
- lib/screens/channel/chat/emote_menu/emote_menu_panel.dart
- lib/screens/channel/stores/chat_assets_store.dart
- lib/screens/channel/stores/chat_assets_store.g.dart
- lib/widgets/section_header.dart
Subscribed emotes are now grouped by channel name rather than lumped all together in one section.
Closes #142
> Improve sorting for subscribed emotes in emote menu

- lib/models/badges.dart
- lib/models/badges.g.dart
- lib/models/channel.dart
- lib/models/channel.g.dart
- lib/models/emotes.dart
- lib/models/emotes.g.dart
- lib/models/stream.dart
- lib/models/stream.g.dart
- lib/models/user.dart
- lib/models/user.g.dart
- test/emote_test.dart
- test/stream_test.dart
- test/user_test.dart
Closes #165
Removes all fields from models that aren't used anywhere in the app. These unused fields cause unnecessary overhead and are prone to bugs in the event of future API changes.
Some of them will likely be re-added in the future in the event a new feature requires them.
> Remove unused model fields

- lib/screens/channel/stores/video_store.dart
Fixes #166.
In order to properly dispose of the video/stream to prevent it from still playing and showing PiP, I made it so that the webview reloads (refreshes) when disposed of. This essentially removes the video from view and ensures that no video component exists for playback.
I initially tried loading a random URL, but the video still did not stop. Loading a random HTML string didn't work either.
> Fix PiP not dismissing on iOS

- android/app/src/main/AndroidManifest.xml
- lib/core/auth/auth_store.dart
Also a potential fix for #169 (needs more investigation).
On Android, app data will always restore by default when reinstalling. This may cause conflicts and issues with old and new tokens, preferences, and values when reading and storing, especially when the backup is really old.
To fix this, I've disabled Auto Backup completely with `android:allowBackup="false"` in the Android app manifest.
I've also added some captures through Sentry in the auth methods so that I'll be able to identify auth issues when they arise (should have done this from the beginning).
> Fix old data restoring on reinstall (Android)

- lib/api/twitch_api.dart
- lib/core/user/user_store.dart
Fixes #169.
Thanks to the detailed reporting in #169, we were able to discover that having a really large list of blocked users was blocking the UI and preventing the login from completing properly.
After logging in, there is an initialization process that involves fetching information regarding the logged-in user. These steps are performed sequentially through fetching with `await`, so the next steps must wait for the previous ones to complete.
When fetching blocked users, the logged-in user could have thousands, if not, hundreds of thousands of blocked users (one reason being bots). This will cause "jank" and essentially freeze the UI until all users have been fetched.
Furthermore, the Twitch API only allows fetching up to 100 blocked users per request, with a limit of 800 requests per …
> Fix large blocked users list preventing login

- lib/screens/channel/chat/chat.dart
- lib/screens/channel/chat/widgets/chat_message.dart
- lib/screens/settings/sections/chat_settings.dart
- lib/screens/settings/sections/video_settings.dart
- lib/screens/settings/stores/settings_store.dart
- lib/screens/settings/stores/settings_store.g.dart
- lib/widgets/alert_message.dart
Closes #171.
Adds a "Paste" button to the right end of the "Message copied" notification in chat. Tapping the button will paste the copied message into the text field, allowing for a more efficient way of copying and sending chat messages.
Also adds an option to have the notification appear at the bottom of the chat rather than the top. This improves ergonomics (since it'll be reachable right above the text field) at the cost of being in the way of the most recent chat message.
> Add paste button for copied messages and option to move notification to the bottom of chat

- lib/screens/channel/chat/chat.dart
- lib/screens/channel/chat/widgets/chat_message.dart
- lib/screens/channel/stores/chat_store.dart
- lib/screens/channel/stores/chat_store.g.dart
When copying messages multiple times back-to-back, the timer used to dismiss the notification automatically will sort of "overlap" and cancel future notifications.
I've added a new `updateNotification` method in the chat store that cleans up the notification logic. Now, the notification timer will just restart every time a new message is copied.
> Fix chat notifications dismissing early

- lib/screens/channel/stores/chat_store.dart
When refactoring the chat in v2.1.0, I forgot to verify that the list of messages doesn't grow to infinity when auto-scroll is off. The "new" chat involves a buffer list for holding messages to be rendered later, so once auto-scroll is disabled, this buffer will grow infinitely.
To address this, I've made it so that once the message buffer reaches a certain limit, the buffer is moved to the visible list of chat messages, and then the buffer is cleared.
> Fix infinite messages in chat when auto-scroll is off

- lib/screens/channel/stores/chat_assets_store.dart
A while back, I made a change in the Future that fetches assets, resulting in a sort of race condition where the global badges override the channel badges with the same name. This resulted in default subscriber badges being shown rather than channel-specific subscriber badges.
To fix it, I've reverted the change so that the global badges are fetched first, THEN the channel badges.
> Fix wrong subcriber badges in chat

- lib/screens/channel/chat/chat.dart
- lib/screens/channel/chat/emote_menu/emote_menu.dart
- lib/screens/channel/stores/chat_store.dart
- lib/screens/channel/video_chat.dart
Adds a button that disconnects and reconnects the chat. This was needed because sometimes when the connection is unstable or the network is switched, the chat will just freeze, requiring the user to navigate and re-enter the channel in order to reconnect.
Now, there is a "Reconnect to chat" button that shows up in a new settings modal.
Also moves the refresh emotes/badges button from the emote menu to the new settings modal.
Also, notifications have been added for the reconnect and refresh emotes action.
> Add the ability to reconnect to chat with notification

- lib/models/irc.dart
When setting the message scale setting above 1.0, display names in chat were misaligned. This was caused by  `alignment: PlaceholderAlignment.middle` missing from the `WidgetSpan`.
Although adding the alignment will technically fix it, using `WidgetSpan` results in display names being oversized. Furthermore, the `InkWell` widget used for making the name tappable causes the splash effect on the name to look weird.
As a fix, I've reverted the display name to use `TextSpan` and added a long tap gesture recognizer, essentially achieving the same behavior. Display names are now properly scaled and there won't be a weird splash effect when holding down the name.
> Fix misaligned chat names when setting msg scale

- lib/main.dart
- lib/screens/channel/channel.dart
- lib/screens/channel/chat/chat.dart
- lib/screens/channel/chat/details/chat_details.dart
- lib/screens/channel/chat/details/chat_modes.dart
- lib/screens/channel/chat/widgets/chat_bottom_bar.dart
- lib/screens/channel/chat/widgets/chat_message.dart
- lib/screens/channel/video/video_overlay.dart
- lib/screens/home/home.dart
- lib/screens/home/stream_list/stream_card.dart
- lib/screens/home/top/categories/category_card.dart
- lib/screens/settings/chat_settings.dart
- lib/screens/settings/stores/settings_store.dart
- lib/screens/settings/stores/settings_store.g.dart
This PR contains the following:
- **Added first message highlights**
- Added options to show/hide first message highlights and alerts
- Changed arrow for resume scroll button
- Reduced title opacity and font-weight on stream cards for consistency
- Renamed the "Followed Streams" tab to just "Following"
- **Moved the settings button from the video overlay to the bottom bar**
- Darkened the dark theme (again)
> Add first message highlights and various tweaks

- lib/screens/channel/chat/widgets/chat_bottom_bar.dart
- lib/screens/settings/chat_settings.dart
- lib/screens/settings/stores/settings_store.dart
- lib/screens/settings/stores/settings_store.g.dart
The emote menu button and "more" button (three dots) are quite close to each other, sometimes resulting in miss-taps. This PR adds an option to have the emote menu button on the left side of the text field instead.
Closes #173
> Add option to have emote menu button on left

- lib/screens/channel/chat/emote_menu/emote_menu.dart
Fixes #188
On the official Twitch app on Android, while the emote menu is open, pressing the back button closes the emote menu instead of navigating back. This PR emulates this behavior for Android.
> Close emote menu when going back on Android

- lib/screens/channel/channel.dart
- lib/screens/settings/chat_settings.dart
- lib/screens/settings/stores/settings_store.dart
- lib/screens/settings/stores/settings_store.g.dart
Closes #195.
Adds a new option that forces the chat to be on the bottom when in landscape mode for those that may prefer having the chat on the bottom instead of on the left or right side. This is useful for tablets and other larger displays which have enough vertical space.
> Add option to force vertical chat in landscape mode

- lib/screens/home/stream_list/stream_list_store.dart
- lib/screens/home/stream_list/streams_list.dart
- lib/screens/home/top/categories/categories.dart
- lib/screens/home/top/categories/categories_store.dart
Fixes #220
Adds a variable that stores the last time that the streams/categories lists were updated and a method that handles checking the timer to update the list if necessary.
Whenever Frosty is resumed or the list appears (i.e., build), the method `checkLastTimeRefreshedAndUpdate` will be called, which updates the lists if it has been more than 5 minutes since the last call.
> Update streams/categories lists when resuming after 5 minutes

- lib/main.dart
- lib/screens/home/home.dart
- lib/screens/onboarding/onboarding_intro.dart
- lib/screens/onboarding/onboarding_login.dart
- lib/screens/onboarding/onboarding_scaffold.dart
- lib/screens/onboarding/onboarding_setup.dart
- lib/screens/onboarding/onboarding_welcome.dart
- lib/screens/settings/account/widgets/profile_card.dart
- lib/screens/settings/chat_settings.dart
- lib/screens/settings/general_settings.dart
- lib/screens/settings/other_settings.dart
- lib/screens/settings/stores/auth_store.dart
- lib/screens/settings/stores/settings_store.dart
Fixes #228
Adds a short onboarding guide on the first launch. Includes (in order of appearance):
1. **Introduction**: provides a brand and brief of Frosty to let the user know they got the right app.
2. **Login**: explains why the user should log in, with the option to skip for later.
3. **Settings setup**: allows immediate customization of some basic options.
4. **Welcome**: provides further details about Frosty (e.g., links to repo and FAQ).
It's relatively simple for now, but I've made it quite functional so that future additions are easy.
> Add onboarding

- lib/screens/channel/video/video_store.dart
On Android, when leaving a channel and disposing of the picture-in-picture functionality, OS versions that don't support auto picture-in-picture would throw an exception. This causes errors to clog up in Sentry.
This fixes it by simply checking if auto pip is available before disposing.
> Fix pip exception on Android

- lib/screens/home/stream_list/large_stream_card.dart
- lib/screens/home/stream_list/stream_card.dart
- lib/widgets/cached_image.dart
Due to the `useOldImageOnUrlChange` parameter defaulting to `true` in the new `FrostyCachedImage` widget, badges and emotes in chat would switch from old/random emote images to their actual ones.
This PR adds a new `useOldImageOnUrlChange` parameter that defaults to `false`.
> Fix badges/emotes in chat switching from old image

- lib/apis/twitch_api.dart
- lib/screens/channel/chat/details/chat_details.dart
- lib/screens/channel/chat/details/chat_details_store.dart
- lib/screens/channel/chat/details/chat_details_store.g.dart
- lib/screens/channel/chat/details/chat_users_list.dart
- lib/screens/channel/chat/stores/chat_store.dart
- lib/screens/channel/chat/widgets/chat_bottom_bar.dart
Sadly, [another Twitch endpoint has gone down](https://discuss.dev.twitch.tv/t/legacy-chatters-endpoint-shutdown-details-and-timeline-april-2023/43161). This time it's the public endpoint for getting all chatters at once for a specific channel.
The ["new" endpoint](https://discuss.dev.twitch.tv/t/new-chatters-api-endpoint-now-available-in-open-beta/40962) in the latest Twitch API is not a viable alternative because it requires moderator permissions and only allows pagination.
This PR contains the next best solution I could think of. Basically, as new messages come in, the sender will be added to the chatters list. This gives us an ephemeral chatters list based on the most recent chat messages.
> Obtain chatters based on chat messages

- lib/screens/channel/chat/stores/chat_store.dart
- lib/screens/channel/chat/stores/chat_store.g.dart
- lib/screens/channel/chat/widgets/chat_bottom_bar.dart
This PR fixes the autocomplete bar not updating after inputting the first character when trying to mention or type emote names.
The root cause is still unclear, but I believe it's due to a recent update to MobX, the package used for state management throughout the app. Based on recent release notes, there were some optimizations and bug fixes. These changes probably caused "bugged/invalid" rebuilds that worked in older versions of Frosty to no longer work in the latest version.
To fix this, I've added an observable `inputText` variable that will keep in sync with the current value of the chat's `TextEditingController`. This will ensure that MobX detects the input changes and accurately rebuilds as the user types.
> Fix chat autocomplete not updating

- lib/screens/channel/video/video.dart
- lib/screens/channel/video/video_store.dart
This PR fixes video playing in the background in chat-only mode.
The issue was caused by the web view still loading the stream URL regardless of whether the video option was on or off.
To fix this, I've moved the URL loading to depend on the widget lifecycle. Therefore, the URL will only be loaded when the `video` widget itself is actually visible.
> Fix audio playing in chat-only mode

- lib/models/irc.dart
- lib/screens/channel/chat/emote_menu/emote_menu_panel.dart
- lib/screens/channel/chat/emote_menu/emote_menu_section.dart
- lib/screens/channel/chat/emote_menu/recent_emotes_panel.dart
- lib/screens/channel/chat/stores/chat_assets_store.dart
- lib/screens/channel/chat/stores/chat_store.dart
Closes #197 and #245.
This PR adds the sub emotes of the current channel to the emote menu under the Twitch -> Channel tab. The emotes will be disabled if you are not subscribed to the channel.
Also fixes a case where enabling turbo emotes would prevent emotes from subbed channels from showing in the emote menu.
Additionally, emotes in the emote menu now use the new tooltip by long-pressing the emote.
> Add Twitch sub emotes to emote menu

- lib/screens/channel/video/video_store.dart
Fixes #279.
This PR simply adds a JavaScript line that hides subtitles on the web video player. This is an iOS-specific fix, where subtitles/cc are enabled by default.
> Hide subtitles on iOS

- lib/apis/seventv_api.dart
- lib/models/emotes.dart
- lib/models/emotes.g.dart
- lib/models/irc.dart
Fixes (#289).
This PR fixes a case where 7TV emotes were not being shown/parsed correctly if the channel had set a custom name for that emote.
With the 7TV V3 API, emotes have 2 different name fields, the first on the top level as `name` and the second in `data` -> `name`. The former will change automatically if the channel has set a custom name for it, while the latter will not change and is the "real" name of the emote.
I mistakenly thought the latter had the behavior of the former and used that field. Now, the former field will be used and checked to see if we should show the real name in the emote details.
> Fix 7TV emotes not using custom names

- lib/models/emotes.dart
- lib/models/emotes.g.dart
Fixes #290.
This PR makes it so that we parse the `flags` field from the 7TV V3 API to check if an emote is zero-width
Previously, the `tags` field was being parsed to determine if it was zero-width. Turns out, not all zero-width emotes have this set (the tags are probably for something else, like for rendering/filtering on clients).
It doesn't seem to be documented, but based on looking at different emotes in the responses, the `flags` field appears to be responsible for the zero-width ability. If set to `0` it means a normal emote and `1` means zero-width. This field is now checked to determine if an emote is zero-width.
> Fix 7TV zero-width emotes not working

- lib/screens/channel/chat/details/chat_details.dart
- lib/screens/channel/chat/emote_menu/recent_emotes_panel.dart
This PR fixes the "Recent" panel in the emote menu not clearing.
During the Material 3 refactor, I forgot to handle the clear behavior when confirming on the alert dialog. I've simply added back the clear method when tapping "Yes" on the alert dialog.
I've also wrapped the recent emote panel with the `Observer` widget so that the clear will be properly rebuilt.
> Fix recent emotes not clearing

- lib/apis/seventv_api.dart
- lib/models/emotes.dart
- lib/models/emotes.g.dart
- lib/models/events.dart
- lib/models/events.g.dart
- lib/models/irc.dart
- lib/screens/channel/channel.dart
- lib/screens/channel/chat/stores/chat_assets_store.dart
- lib/screens/channel/chat/stores/chat_assets_store.g.dart
- lib/screens/channel/chat/stores/chat_store.dart
- lib/screens/channel/chat/stores/chat_store.g.dart
- lib/screens/channel/chat/widgets/chat_user_modal.dart
- lib/screens/channel/chat/widgets/reply_thread.dart
- lib/screens/channel/video/video_bar.dart
- lib/screens/home/search/search_results_channels.dart
- lib/screens/home/stream_list/large_stream_card.dart
- lib/screens/home/stream_list/stream_card.dart
- lib/screens/settings/account/blocked_users.dart
- lib/utils.dart
This PR adds support for 7TV events so that emote additions and removals will automatically reflect in chat.
Previously when a channel added/removed a 7TV emote, we'd have to manually refresh the chat in order for it to show up.
Now with the [7TV events API](https://github.com/SevenTV/EventAPI), there's a listener that will automatically add/remove emotes from the assets store.
> Add support for 7TV emote update events

- lib/screens/channel/video/video_store.dart
- lib/screens/channel/video/video_store.g.dart
I was looking into why stream qualities weren't displaying for me on the custom overlay, and found it was occurring because after clicking the :gear: settings button on the player, the menu doesn't appear until a split second later.
To fix this, I've updated the stream quality methods to use a new `asyncQuerySelector` instead of `document.querySelector`. I had to apply the same fix to the latency stats to ensure consistent stream quality behaviour, as they also interact with the settings menu.
This change to using async JS code means that awaiting for `videoWebViewController.runJavaScript` no longer guarantees that the previous task actually completed, which was causing issues with the current `defaultToHighestQuality` logic. I resolved this by updating this setting to call a new …
> Fix quality selection and latency stats using an asyncQuerySelector

- lib/screens/channel/chat/details/chat_details.dart
- lib/screens/channel/chat/stores/chat_store.dart
Entering chat-only mode requires navigating through a few layers of settings menus every time. This PR adds a new button in the chat menu that lets you quickly toggle chat-only mode (aka show/hide the video).
> Add quick toggle for chat-only mode

- lib/models/badges.g.dart
- lib/models/chatters.g.dart
- lib/models/emotes.g.dart
- lib/models/events.g.dart
- lib/models/stream.g.dart
- lib/screens/channel/chat/stores/chat_store.dart
- lib/screens/channel/chat/widgets/chat_bottom_bar.dart
- lib/screens/channel/video/video_store.dart
- lib/screens/settings/chat_settings.dart
- lib/screens/settings/stores/settings_store.dart
- lib/screens/settings/stores/settings_store.g.dart
The stream latency will sometimes gradually increase due to connection or player issues. This causes the stream to further become out of sync with the chat despite setting a message delay setting. 
This PR adds a new setting toggle that makes the chat latency be in sync with the stream latency. There might be some unintended side effects so it's labeled experimental.
> Add option to sync message delay with stream latency

- lib/models/irc.dart
- lib/screens/home/stream_list/stream_card.dart
- lib/widgets/photo_view.dart
- pubspec.lock
- pubspec.yaml
This PR adds the ability to long-press on a stream card thumbnail or tap an emote or badge in the details bottom sheet to show a full-screen zoomable photo view.
> Add photo view for thumbnails, emotes, and badges

- lib/apis/twitch_api.dart
- lib/models/irc.dart
- lib/screens/channel/channel.dart
- lib/screens/channel/chat/stores/chat_store.dart
- lib/screens/channel/chat/stores/chat_store.g.dart
- lib/screens/channel/chat/widgets/chat_message.dart
- lib/screens/onboarding/onboarding_setup.dart
- lib/screens/settings/chat_settings.dart
- lib/screens/settings/stores/settings_store.dart
- lib/screens/settings/stores/settings_store.g.dart
This PR adds an option that uses the [recent messages API](https://recent-messages.robotty.de/api) to fill in historical messages when connecting to chat. The historical messages will have 50% opacity to distinguish them in chat. Off by default to be opt-in.
Closes #358.
> Add option to enable historical recent messages in chat

- assets/release-notes.md
- lib/screens/home/home.dart
- lib/screens/settings/other_settings.dart
- lib/screens/settings/widgets/release_notes.dart
- pubspec.lock
- pubspec.yaml
This PR adds a release notes page when launching the app on a new release. Uses the flutter markdown package to convert a local markdown file into a release notes page.
> Add release notes on launch

- lib/main.dart
- lib/screens/channel/video/video_overlay.dart
- lib/screens/channel/video/video_store.dart
- lib/screens/channel/video/video_store.g.dart
- lib/screens/settings/video_settings.dart
- lib/utils.dart
Fixes https://github.com/tommyxchow/frosty/issues/341
Example screenshot of the video player on iPad, using the custom overlay with "Default to highest quality" enabled.
> Show video quality settings on iPad

- lib/screens/home/search/search_store.dart
When searching for games like "TEKKEN 8" or "Street Fighter 6", I have to scroll down quite far to find the actual category.
This PR moves category search results which exactly match the search query to the top of the list.
Example when searching "street fighter 6":
| Before | After |
|-|-|
|![sf6-before](https://github.com/user-attachments/assets/ff7646c6-0913-485a-bf08-7f7a4cf52b9b)|![sf6-after](https://github.com/user-attachments/assets/963673a0-b6ad-48b5-a12d-9ac35ce6bd5d)|
> Move exact matches of searched categories to the top

- lib/screens/onboarding/onboarding_login.dart
- lib/screens/settings/stores/auth_store.dart
1. Constraints the height of the cookie banner description to 20vh and makes it scrollable.
2. Adds another workaround instruction courtesy of #380, accessible by tapping the question mark in the toolbar.
Closes #380.
> Fix and add workaround for cookie banner blocking login

- lib/screens/channel/video/video_store.dart
This PR fixes two issues I've occasionally been running into when opening a stream.
1. [Add window-level promise queuing and _asyncQuerySelector](https://github.com/tommyxchow/frosty/commit/c338c609246ec9b9f7e33c87ec002fe31c8dfb3a):
- When defaulting to the highest quality with the custom overlay, sometimes the highest quality will be "selected" in the overlay, but the actual playback will still be using the default "Auto" quality. Refreshing the stream or manually reselecting the highest quality are some workarounds.
- I believe this is caused by a race condition where `_listenOnLatencyChanges` and `_setStreamQualityIndex` attempt to interact with the settings elements at the same time.
- Prevent this by introducing a promise queue.
2. [Use _asyncQuerySelector to initialize video …
> Improve initial playback stability

- lib/screens/channel/chat/stores/chat_store.dart
- lib/screens/settings/chat_settings.dart
- lib/screens/settings/stores/settings_store.dart
- lib/screens/settings/stores/settings_store.g.dart
- lib/screens/settings/widgets/settings_muted_words.dart
This PR adds the ability for users to mute specific keywords in the chat.
It adds a section in the chat settings. Besides the bottom sheet with a text field, there is a switch that makes the app only match whole words instead of words containing the keyword (for example, if someone wants to mute "W"s but doesn't want words with "w" to be filtered). 
Related to issue #400 
https://github.com/user-attachments/assets/b067f4ed-f4d4-4ff3-b15f-dfb8cadf99de
> Add ability to mute keywords from chat

- lib/screens/channel/video/video_store.dart
Continues https://github.com/tommyxchow/frosty/pull/411. Looks like this PR didn't fully fix the issue, as shown in the following screenshot.
The player is stuck in the paused state. The latency stat is showing though, which suggests the promise queue is working.
This PR adds a `if (!videoElement.paused)` check, because subscribing to the `playing` event when the video is already playing doesn't emit the event.
> Further improve initial playback stability

- lib/screens/channel/chat/stores/chat_assets_store.dart
- lib/screens/channel/chat/stores/chat_store.dart
In a previous commit, the `catchError` in the 7TV emotes future was accidently changed to use the `onBadgeError` function, causing a type error to throw and making the rest of the emote futures to cancel/end early. When a channel doesn't have any 7TV emotes, the future will fail and call the error handler by default.
Fixed by reverting the error handler function.
Fixes #425
> fix missing emotes on channels that don't have 7tv enabled

- lib/apis/seventv_api.dart
- lib/models/emotes.dart
- lib/models/emotes.g.dart
- lib/models/events.g.dart
Fixes #440 #422
This PR fixes a case where one or more 7TV emotes that are still processing cause the emote processing/parsing to fail, throwing a `Bad state: No element` error and returning no 7TV emotes. Was happening on the AlveusSanctuary  and Yogscast channels.
Example in the AlveusSanctuary channel:
- 7TV data: https://7tv.io/v3/users/twitch/636587384):
- One of the emotes (JSON below) an empty array in the `host.files`, causing the error to throw.
- Going to the emote on 7TV's site, the emote is still processing (https://7tv.app/emotes/01JS0D2GFVZHRZFV5DM4E7HZBY)
- Fix was to use the `OrNull` versions for the `.first` and `.last` getters
```json
{
"id": "01JS0D2GFVZHRZFV5DM4E7HZBY",
"name": "Bowlgegorge",
"flags": 0,
"timestamp": 1744844177915,
"actor_id": …
```
> fix some channels missing 7tv emotes
